version: '3.7'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node

    kinaba:
        image: docker.elastic.co/kibana/kibana:6.5.4
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch